"""empty message

Revision ID: 2211bc358281
Revises: 246ee4d57789
Create Date: 2024-04-30 11:48:42.990708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2211bc358281'
down_revision = '246ee4d57789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.VARCHAR(), nullable=True))

    op.drop_table('comentario')
    # ### end Alembic commands ###
