"""empty message

Revision ID: 5cd11d4e39b2
Revises: 2211bc358281
Create Date: 2024-04-30 11:58:37.933808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd11d4e39b2'
down_revision = '2211bc358281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'contato', ['contato_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contato_id')

    # ### end Alembic commands ###
